# Generated by Django 5.2.4 on 2025-07-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_created_at_question_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created_at',
            new_name='created_to',
        ),
    ]
