# Generated by Django 5.2.4 on 2025-07-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_staticfiletest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticfiletest',
            old_name='Title',
            new_name='title',
        ),
    ]
