# Generated by Django 5.2.4 on 2025-07-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_title_staticfiletest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfiletest',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
